# Generated by Django 2.2.3 on 2019-07-27 16:47

from countries.countryinfo import CountryInfo
from django.db import migrations
# from countries.models import Country

# CountryInfo.Write_to_xlsx()
ext = CountryInfo.Extract_country_dail_prefix()
names = CountryInfo.country_name()
t_zone = CountryInfo.timezones()


def seed_countries(apps, schema_editor):
    Country = apps.get_model('countries', 'Country')
    countries = []
    # was getting array out of range so looped the len(t_zone) instead
    for i in range(len(t_zone)):
        country = Country(
            name=names[i],
            country_code=ext[i],
            time_zone=t_zone[i],
        )
        countries.append(country)
    Country.objects.bulk_create(countries)


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_countries)
    ]
