# Generated by Django 2.2.3 
from countries.countryinfo import CountryInfo
from django.db import migrations

def seed_countries(apps, schema_editor):
	CountryInfo.Write_to_xlsx()
	ext = CountryInfo.Extract_idd()
	names = CountryInfo.country_name()
	t_zone = CountryInfo.timezones()
	Country = apps.get_model('countries', 'Country')
	countries = []
	for i in range(len(t_zone)):
		country = Country(
            name=names[i],
            country_code=ext[i],
            time_zone=t_zone[i])
		countries.append(country)
	Country.objects.bulk_create(countries)


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_countries)
    ]
